/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: dy                                                    *
* Dimensions:  47 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmdy;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsdy[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _Paldy = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acdy[] = {
  ________, _____X_X, X_XXX_X_, XX_X_X__, X_______, ________,
  ________, ____XXXX, XXXXXXXX, XXXXX___, __X_____, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  __XXXXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX, XXXX____,
  __XXXXXX, XXXXXXXX, XX_XXX__, __XXXXXX, XXXXXXXX, XXXX____,
  _XXXXXXX, XXXXXXXX, X_______, ____XXXX, XXXXXXXX, XXXX____,
  _XXXXXXX, XXXXXXX_, ________, ____XXXX, XXXXXXXX, XXXX____,
  _XXXXXXX, XXXXXX__, ________, _____XXX, XXXXXXXX, XXXXX___,
  _XXXXXXX, XXXXX___, ________, ________, XXXXXXXX, XXXXX___,
  _XXXXXXX, XXXX____, ________, ________, _XXXXXXX, XXXXX___,
  XXXXXXXX, XXX_____, ________, ________, __XXXXXX, XXXXX___,
  _XXXXXXX, X_______, ________, ________, ____XXXX, XXXXX___,
  _XXXXXXX, ___X____, ________, ________, ____XXXX, XXXXX___,
  _XXXXXX_, _XXXXXX_, ________, _____X_X, XXX__XXX, XXXXX___,
  _XXXXXX_, XXXXXXXX, XX______, ____XXXX, XXXX__XX, XXXX____,
  _XXXXXX_, XXXXXXXX, XX______, ___XXXXX, XXXXX_XX, XXXX____,
  __XXXXX_, XXX_____, ________, ________, ___XX__X, XXXX____,
  ___XXX__, ________, ________, ________, ____XX_X, XXX_____,
  __XXXX__, ________, ________, ________, _______X, XXX_____,
  ___XXX__, _____X_X, ________, ________, _______X, XXX_____,
  __X_XX__, __XXXXXX, X_______, ____XXXX, XX_____X, XX______,
  __XXXX__, ___X__X_, ________, _____XXX, _XX_____, XXXX____,
  _XX_XX__, ________, ________, ________, _______X, XX_X____,
  ____XX__, ________, ________, ________, ________, XX_XX___,
  ____XX__, ________, ________, ________, ________, XX______,
  ___XX___, ________, ________, ________, ________, XX______,
  _____X__, ________, ________, ________, ________, X_______,
  ____XX__, ________, ________, ________, ________, X_______,
  _____X__, ________, ________, ________, ________, XX______,
  _____X__, ________, ________, ________, ________, ________,
  _____X__, ________, ________, ________, _______X, ________,
  ________, ________, ___X____, _X______, ________, ________,
  ________, ________, __XXXXXX, XXX_____, ________, ________,
  ________, ________, ____X_X_, X_X_____, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, X_X_XXXX, XX_X____, ________, ________,
  ________, ________, XXXXX_X_, X_XXX___, ________, ________,
  ________, ________, __X_____, ________, ________, ________,
  ________, ________, ______X_, X_______, ________, ________,
  ________, ________, ___XXXXX, X_______, ________, ________,
  ________, ________, ____X___, ________, ___X____, ________,
  ________, __XX____, ________, ________, __XX____, ________,
  ________, ___XX___, ________, ________, _XXX____, ________,
  ________, ___XXX__, ________, _______X, XXX_____, ________,
  ________, ___XXXX_, ________, ______XX, XXXX____, ________,
  ________, ___XXXXX, ________, _____XXX, X___X___, ________,
  ________, _XXXXXXX, XX___X_X, __XXXXXX, ____XXX_, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXX__, _____XXX, X_______,
  ______XX, XXX____X, XXXXXXXX, XXXX____, ______XX, XX______
};

GUI_CONST_STORAGE GUI_BITMAP bmdy = {
  47, // xSize
  64, // ySize
  6, // BytesPerLine
  1, // BitsPerPixel
  _acdy,  // Pointer to picture data (indices)
  &_Paldy   // Pointer to palette
};

/*************************** End of file ****************************/
