/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: ly                                                    *
* Dimensions:  45 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmly;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsly[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _Pally = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acly[] = {
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXX_, ________, ______XX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXX____, ________, ________, XXXXXXXX, XXXXX___,
  XXXXXXXX, XX______, ________, ________, _XXXXXXX, XXXXX___,
  XXXXXXXX, X_______, ________, ________, __XXXXXX, XXXXX___,
  XXXXXXXX, X_______, ________, ________, ___XXXXX, XXXXX___,
  XXXXXXXX, ________, ________, ________, _____XXX, XXXXX___,
  XXXXXXX_, ________, ________, ________, _______X, XXXXX___,
  XXXXXXX_, ________, ________, ________, _______X, XXXXX___,
  XXXXXX__, ________, ________, ________, ________, XXXXX___,
  XXXXXX__, ________, ________, ________, ________, XXXXX___,
  XXXXXX__, ________, ________, ________, ________, XXXXX___,
  XXXXXX__, ________, ________, ______XX, XXXX____, _XXXX___,
  XXXXX___, __XXXXXX, ________, _____XX_, X__XX_X_, _XXXX___,
  XXXXX__X, XXXXXXXX, X_______, ________, ________, __XXX___,
  XXXX___X, X_______, ________, ________, ________, __XXX___,
  XXXX____, ________, ________, ________, ________, ___XX___,
  XXX_____, ________, ________, ________, ____XXX_, ___XX___,
  XXX_____, XXXX___X, ________, ___XX_XX, _______X, XXXXX___,
  XXXXXXX_, _____XXX, ___XXXXX, XXX__XXX, XXXX____, XXXXX___,
  XXXXXX__, __XXXXXX, XX__XXXX, XX__XXXX, XXXXXX__, X__XX___,
  XX___X__, XXXXXXXX, _X__XXX_, XX______, _____X__, X___X___,
  XX___X__, _X______, ____XX__, _X______, ________, X___X___,
  XX___X__, ________, ____XX__, _XX_____, ________, X___X___,
  XX______, ________, ____X___, _XX_____, ________, X___X___,
  XX____X_, ________, ___XX___, __X_____, ________, ____X___,
  XX____X_, ________, ___X____, ___X____, _______X, ____X___,
  XX_____X, ________, _XXX____, ___X__X_, ____X___, ____X___,
  XX______, _X____X_, ________, ________, ________, ________,
  _XX_____, ________, ________, ________, ________, ___X____,
  __X_____, ________, ________, ________, ________, ___X____,
  _XX_____, ________, _____X__, __X_____, ________, __XX____,
  _XXX____, ________, ___XXXXX, XXXXX___, ________, __XX____,
  __XX____, ________, __XXXXXX, XXXXX___, ________, ________,
  ________, ________, ____XXXX, X_______, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ______X_, _XX___X_, ________, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ________, XXXXX___, X__XXXXX, ________, X_______,
  __XXXX__, ________, ________, ________, ________, XXX_____,
  XXXXXXX_, ________, ________, ________, _______X, XXX_____,
  XXXXXXX_, ________, ________, ________, ______XX, XXXX____,
  XXXXXXXX, ________, ________, ________, _____XXX, ___XX___,
  XXXXXXXX, XX______, ________, ________, ____XXXX, ____X___,
  XXXXXXXX, XXX_____, ________, ________, ___XXXXX, ________,
  XXXXXXXX, XXXX____, ________, ________, __XXXXXX, ________,
  X_XXXXXX, XXXXX___, ________, ________, _XXXXXXX, ________,
  XXXXXXXX, XXXXXXX_, ________, ________, XXXXXXXX, ________,
  XXXXXXXX, XXXXXXXX, ________, ______XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, X____XX_, _X___XXX, XXXXXXXX, X_______
};

GUI_CONST_STORAGE GUI_BITMAP bmly = {
  45, // xSize
  64, // ySize
  6, // BytesPerLine
  1, // BitsPerPixel
  _acly,  // Pointer to picture data (indices)
  &_Pally   // Pointer to palette
};

/*************************** End of file ****************************/
