/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: hjl                                                   *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmhjl;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorshjl[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palhjl = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _achjl[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ____XXXX, XXXX____, ________, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXX__, ________, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ________,
  ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, _____XXX, XXXXXXXX, X_______, _X_XXXXX, XXXXXXXX, XXX_____, ________,
  ________, _____XXX, XXXXXXX_, ________, _______X, _XXXXXXX, XXX_____, ________,
  ________, ______XX, X_______, ________, ________, __XXXXXX, XXX_____, ________,
  ________, _____XXX, X_______, ________, ________, __XXXXXX, XXX_____, ________,
  ________, ______XX, ________, ________, ________, __XXXXXX, XX______, ________,
  ________, ______XX, _____XXX, X_______, ____XXXX, XXXXXXXX, XX______, ________,
  ________, ______X_, ________, ________, ___XXXXX, XXXX_XXX, XX______, ________,
  ________, ______X_, ________, ________, ________, ___X__XX, XX______, ________,
  ________, ________, _______X, X_______, ________, ___X___X, X_______, ________,
  ________, ________, ______XX, XX______, ____XXXX, XXXXX__X, XXX_____, ________,
  ________, ________, ________, ________, ______XX, _XXX___X, XXXX____, ________,
  ________, ________, ________, ________, ________, _______X, X_XX____, ________,
  ________, ________, ________, ________, ________, _______X, XXX_____, ________,
  ________, ________, ________, ________, ________, ________, XX______, ________,
  ________, ________, ________, ________, ________, _______X, _X______, ________,
  ________, ________, ________, ________, ________, ________, _X______, ________,
  ________, ________, ________, ____X___, XX______, ____X___, ________, ________,
  ________, ________, ________, ________, _XX_____, __XXX___, ________, ________,
  ________, ________, ________, ________, ________, _XXX____, ________, ________,
  ________, ________, ________, ________, ________, _XXX____, ________, ________,
  ________, ________, ________, ______XX, XXXX____, _XXX____, ________, ________,
  ________, ________, ________, ________, __XXX___, XXX_____, ________, ________,
  ________, ________, ________, ________, ______XX, XXX_____, ________, ________,
  ________, ________, ________, ________, ___XXXXX, XXX_____, ________, ________,
  ________, ________, ________, ________, ___XXXXX, XXXX____, ________, ________,
  ________, ________, ________, ________, ____XXXX, XXXX____, ________, ________,
  ________, ________, ________, ________, ___XXXXX, XXXX____, ________, ________,
  ________, ________, ________, ________, __XXXXXX, XXXX____, ________, ________,
  ________, ________, __XX____, ________, _XXXXXXX, XXXXXXX_, ________, ________,
  ________, ________, _XXX____, _______X, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ________, XXXX____, ________, _XXXXXXX, XXXXXXXX, X_______, ________,
  ________, _______X, XXXX____, ________, __XXXXXX, __XXXXXX, XX______, ________,
  ________, ______XX, XXXX____, ________, ___XXXX_, ___XXXXX, XXX_____, ________,
  ________, ____XXXX, XXXXX___, ________, ___XXX__, ____XXXX, XXXXX___, ________,
  ________, __XX__XX, XXXXX___, ________, ___XXX__, ___XXXXX, XXXXX___, ________,
  ______XX, XXXX__XX, XXXXXX__, ________, ___XX___, ___XXXXX, XXXXXXXX, ________,
  XXXXXXXX, XXX___XX, XXXXXXXX, ________, ________, ___XXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XX_____X, XXXXXXXX, X_______, ________, __XXXXXX, XXXXX__X, XXXXXXXX,
  XXXXXXXX, X______X, XXXXXXXX, XXX_____, ________, _XXXXXXX, XXXXX___, XXXXXXXX,
  XXXXXXX_, ________, XXXXXXXX, XXXXX___, ________, XXXXXXXX, XXXX____, _XXXXXXX,
  XXXXXX__, ________, _XXXXXXX, XXXXXXXX, ______XX, XXXXXXXX, XXX_____, __XXXXXX,
  XXXXX___, ________, _XXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, XX______, ___XXXXX,
  XXXXX___, ________, __XXXXXX, XXXX____, ________, XXXXXXXX, ________, ___XXXXX,
  XXXX____, ________, ___XXXXX, X_______, ________, ________, ________, ____XXXX,
  XXX_____, ________, ________, ________, ________, ________, ________, _____XXX,
  XX______, ________, ________, ________, ________, ________, ________, ______XX,
  X_______, ________, ________, ________, ________, ________, ________, ______XX
};

GUI_CONST_STORAGE GUI_BITMAP bmhjl = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _achjl,  // Pointer to picture data (indices)
  &_Palhjl   // Pointer to palette
};

/*************************** End of file ****************************/
