/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: hsk                                                   *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmhsk;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorshsk[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palhsk = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _achsk[] = {
  XXXX____, ________, ______XX, XXXXXXXX, XXXXXXXX, X_______, ________, XXXXXXXX,
  XXXX____, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, XXXXXXXX,
  XXXX____, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, _XXXXXXX,
  XXXX____, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, _XXXXXXX,
  XXXX____, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _XXXX___,
  XXXX____, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  XXXXX___, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  XXXXX___, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________,
  __X_____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________,
  ________, ___XXXXX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXXX__, ________,
  __XXXXXX, XX_XXXXX, XXXXXX__, ________, ___XXXXX, XXXXXXXX, XXXXXX__, ________,
  __XXXXXX, XX_XXXXX, XX______, ________, _____XXX, XXXXXXXX, XXXXX__X, ____X_X_,
  __XXXXXX, XXXXXXXX, X_______, ________, _______X, XXXXXXXX, XXXXX__X, XXXXXXXX,
  ________, _____XXX, ________, ________, ________, _XXXXXXX, XXXX___X, XXXXXXXX,
  ________, _____XXX, __XXX___, ________, _______X, XXXXXXXX, XXXX___X, XX__XXXX,
  _XXXXXXX, XXXXXXX_, _XXXXXXX, X_______, _____XXX, XXXXXXXX, XXXX___X, XX__XXXX,
  _XXXXXXX, XXXXXXX_, _XX___XX, XXX_____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  _XXXXXXX, XXXXXXX_, ________, _XXXX___, __XXXXX_, _XXXXXXX, XXXXXXXX, XXXXXXXX,
  _XXXXXXX, XXXXXXX_, ________, _X______, _XXXXXX_, _XXXXXXX, XXXXXXXX, XXXXXXXX,
  _XXXXXXX, XXXXXXX_, ____XXXX, XXXX____, _XX__XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X______X, XXX_X___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X,
  XXXXXXXX, XXXXXX_X, X_______, ____X___, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, X_______, ____X___, _XXX____, ____XXXX, XX__XXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXX_, ________, ____X___, _XXX____, _____XXX, XXX__XX_, XXXXXXX_,
  XXXXXXXX, XX______, ________, ________, __XX____, _____XXX, XX__XXX_, XXXXXXXX,
  XXXXXXXX, ________, ________, ________, __XXX___, ______XX, XXXXXXX_, XXXXXXXX,
  XXXXXXX_, ________, ________, ________, __XXXX__, _____XXX, XXXXXXX_, ____XXXX,
  XXXXXX__, ________, ________, ________, ____XX__, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXX____, ________, ________, ________, __XXXX__, ___XXXXX, XXXXX_XX, _XXXX___,
  XXX_____, ________, ________, ________, _XXXXXX_, ___XXXXX, XXXX_XXX, __X_____,
  XX______, ________, ________, ________, XXXXXXX_, ____XXXX, XXX_XXX_, X_______,
  XX______, ________, ________, ________, __XXXX__, ___XXXXX, XX_XXX__, ________,
  X_______, ________, ________, ________, _____X__, _XXXXXXX, XXXXXXXX, XX______,
  XX______, ________, ________, ________, __XXXXXX, XXXXXXXX, X_XXXXXX, X_______,
  XX______, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________,
  XX______, ________, ____XX__, ________, __XXXXXX, XXXX_XXX, XXXXX___, ________,
  XX______, ________, ____XXX_, ________, __XXXXXX, XXX__XX_, XXXX____, ________,
  XX______, ________, ____XXX_, _____XXX, XXXXXXXX, X___XX__, XXXX____, ________,
  XX______, ________, _____XXX, ________, _XXXXXXX, X__XXX_X, XXX_____, ________,
  XXX__XX_, ________, _____XXX, X_______, ____XXX_, ___XX__X, XX______, ________,
  XXXXXXX_, ________, ______XX, XXX_____, ___XXX__, __XXX_XX, X_______, ________,
  XXXXXXXX, ________, _______X, XXXXX___, _XXXX___, _XXX__XX, ________, ________,
  XXXXXXXX, X_______, ________, _XXXXXXX, XXX_____, _XXX_XXX, ________, ________,
  XXXXXXXX, XX______, ________, ________, ________, XXXXXXX_, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, _______X, XXXXX___, ________, ________,
  XXXXXXXX, XXXX____, ________, ________, ______XX, XXXX____, ________, ________,
  XXXXXXXX, XXXXX___, ________, ________, ______XX, _XXXX___, ________, ________,
  XXXXXXXX, XXXXX___, ________, ________, ________, __XX_X__, ________, ________,
  XXXXXXXX, XXXXXX__, ________, ________, ____X___, ___X____, ________, ________,
  XXXXXXXX, XXXXXXX_, ________, ________, _X______, ________, ________, __XX____,
  XXXXXXXX, XXXXXXXX, ________, ______XX, ________, ________, __X_____, _XX_____,
  XXXXXXXX, XXXXXXXX, X_______, _____X__, ________, _______X, X_XX____, _XXXXX__,
  XXXXXXXX, XXXXXXXX, X_______, _X__X___, ________, _______X, XXXX____, XXXXXX__
};

GUI_CONST_STORAGE GUI_BITMAP bmhsk = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _achsk,  // Pointer to picture data (indices)
  &_Palhsk   // Pointer to palette
};

/*************************** End of file ****************************/
